defaults: &defaults
  adapter: mysql
  username: root
  password: root
  host: localhost

development:
  database: spacedemo_development
  <<: *defaults

test:
  adapter: mysql
  database: spacedemo_test
  <<: *defaults

production:
  database: spacedemo_production
  <<: *defaults
